# Generated by Django 6.1.1 on 2026-09-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_out',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
